# docker-compose -f docker-compose-create-certs.yml run --rm create_certs
# reference: https://soyoung-new-challenge.tistory.com/115

version: '2.2'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: create_certs
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs;
        fi;
        chown -R 1000:0 /certs
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - escerts:/certs
      - .:/usr/share/elasticsearch/config/certificates

volumes:
  escerts:
    driver: local
